### ISSUE TITLE
identifiers that don't have a value specified

### ISSUE THREAD

**Issue by moaazsidat** [armon/pypred#14]
Hey @armon 

I'm trying to determine the best way to figure out what values need to be provided by the document for a given `Predicate(...)`, essentially this would be the `literals` that are not `static` strings.

I'm imagining the API to be something like 
```
p = Predicate("name is 'Jack' and friend_name is 'Jill'")
p.fields = ['name', 'friend_name'] 
```

Is there a way to achieve this within the existing API?

**Comment by armon** [comment]
@moaazsidat You pass those in during the call to `evaluate()` or `analyze()`.

To extend your example:
```
p = Predicate("name is 'Jack' and friend_name is 'Jill'")
p.evaluate({"name": "Armon", "friend_name": "Alex"})
p.evaluate({"name": "Jack", "friend_name": "Jill"})
```

**Comment by moaazsidat** [comment]
@armon yep, I get the existing usage, by I'm trying to determine for a given `Predicate`, what are all the values that I _should_ pass, or are needed.

Basically imagining a case where I don't know what the `Predicate` is, and am simply a provider of variables. Need to know what variables to provide for evaluation.

**Comment by armon** [comment]
@moaazsidat There isn't a specific API for it, but you could probably do it by using the `tile` method (https://github.com/armon/pypred/blob/master/pypred/tiler.py#L129) and having a simple pattern (https://github.com/armon/pypred/blob/master/pypred/tiler.py#L40) with a pattern like "types:Literal" and then in the call back function just pull out the `value` property.

Something like:

```
literals = []
tile(predicate.ast, SimplePattern("types:Literal"), lambda p: literals.append(p.value))
```

**Comment by moaazsidat** [comment]
yep, that helps
however that would give back all Literals, and not just fields that need values to be passed for evaluation. so the result of doing the above would be 

```
literals == ['name', "'Jack'", 'friend_name', "'Jill'"]
```
are there any ways to distinguish between a 'field' literal, `name` vs. string literal, `"Jack"`? 
inspecting the ast, looks like they're being represented in the same way? 
(don't want to resort to something too hacky by trying to determine string literal based on the presence of string quotes)

**Comment by armon** [comment]
@moaazsidat The predicate will call `static_resolve` to see if its static (https://github.com/armon/pypred/blob/master/pypred/predicate.py#L30) and you could just do something like that as well.

```
[l for l in literals if type(predicate.static_resolve(l)) == ast.Undefined]
```

**Comment by moaazsidat** [comment]
yep, that works 👍, thanks a ton, marking this as resolved.
